### ISSUE TITLE
Fail to show method shortcut in py.

### ISSUE THREAD

**Issue by tjlcast** [openpilot-hub/devpilot-vscode#4]
When I click "Enable method shortcut". There is nohting shown in my python method.

![image](https://github.com/user-attachments/assets/0a975312-284a-41c6-8c48-ee9db345ea6c)

![image](https://github.com/user-attachments/assets/dc2c01d4-e4a6-4fd3-b396-aad2177238a8)

 I think it should show some shortcuts above functions for me.

**Comment by xiangtianyu** [comment]
You may close and reopen the file, it will not refresh the file you are opened.

**Comment by tjlcast** [comment]
> You may close and reopen the file, it will not refresh the file you are opened.

I have reopened VSCode and the file, it didn't work. 

And I found that it only shows in Java files, but does not show in .cpp and .py files.

So this extension only support Java?

**Comment by elvinzhu** [comment]
Fixed in v1.6.3， pls upgrade！ @tjlcast
